import { Document, Page, Text, View } from "@react-pdf/renderer";
import { createStyles, formatDate, type PdfBranding } from "./styles";
import { PdfHeader } from "./pdf-header";
import { StatusBadgePdf, SummaryBox, FilterSummaryText, equipmentClassLabels, applianceTypeLabels } from "./test-tag-pdf-shared";

interface Props {
  org: { name: string; email?: string; phone?: string; address?: string; branding?: PdfBranding; logoData?: string | null; iconData?: string | null };
  data: {
    items: {
      testTagId: string; description: string; equipmentClass: string; applianceType: string;
      make: string | null; modelName: string | null; serialNumber: string | null; location: string | null;
      lastTestDate: string | null; nextDueDate: string | null; status: string;
      asset?: { assetTag: string } | null; bulkAsset?: { assetTag: string } | null;
    }[];
    statusCounts: Record<string, number>;
    complianceRate: number;
    total: number;
  };
  filterSummary?: Record<string, string | undefined>;
}

export function TestTagRegisterPDF({ org, data, filterSummary }: Props) {
  const s = createStyles(org.branding);
  const colWidths = [58, 100, 42, 50, 55, 50, 50, 45];

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={s.page}>
        <PdfHeader
          orgName={org.name}
          orgDetails={[org.email, org.phone, org.address].filter(Boolean).join(" | ")}
          docTitle="Test & Tag Register"
          docMeta={`Generated: ${formatDate(new Date())}`}
          branding={org.branding}
          logoData={org.logoData}
          iconData={org.iconData}
          styles={s}
        />

        {filterSummary && <FilterSummaryText filters={filterSummary} />}

        <SummaryBox items={[
          { label: "Total", value: data.total },
          { label: "Current", value: data.statusCounts["CURRENT"] || 0 },
          { label: "Due Soon", value: data.statusCounts["DUE_SOON"] || 0 },
          { label: "Overdue", value: data.statusCounts["OVERDUE"] || 0 },
          { label: "Failed", value: data.statusCounts["FAILED"] || 0 },
          { label: "Not Tested", value: data.statusCounts["NOT_YET_TESTED"] || 0 },
          { label: "Compliance", value: `${data.complianceRate}%` },
        ]} />

        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.th, { width: colWidths[0] }]}>Tag ID</Text>
            <Text style={[s.th, { width: colWidths[1] }]}>Description</Text>
            <Text style={[s.th, { width: colWidths[2] }]}>Class</Text>
            <Text style={[s.th, { width: colWidths[3] }]}>Type</Text>
            <Text style={[s.th, { width: colWidths[4] }]}>Make/Model</Text>
            <Text style={[s.th, { width: colWidths[5] }]}>Last Test</Text>
            <Text style={[s.th, { width: colWidths[6] }]}>Next Due</Text>
            <Text style={[s.th, { width: colWidths[7] }]}>Status</Text>
          </View>
          {data.items.map((item, i) => (
            <View key={i} style={i % 2 === 0 ? s.tableRow : s.tableRowAlt}>
              <Text style={[s.td, { width: colWidths[0] }]}>{item.testTagId}</Text>
              <Text style={[s.td, { width: colWidths[1] }]}>{item.description}</Text>
              <Text style={[s.td, { width: colWidths[2] }]}>{equipmentClassLabels[item.equipmentClass] || item.equipmentClass}</Text>
              <Text style={[s.td, { width: colWidths[3] }]}>{applianceTypeLabels[item.applianceType] || item.applianceType}</Text>
              <Text style={[s.td, { width: colWidths[4] }]}>{[item.make, item.modelName].filter(Boolean).join(" ") || "-"}</Text>
              <Text style={[s.td, { width: colWidths[5] }]}>{formatDate(item.lastTestDate)}</Text>
              <Text style={[s.td, { width: colWidths[6] }]}>{formatDate(item.nextDueDate)}</Text>
              <View style={{ width: colWidths[7] }}><StatusBadgePdf status={item.status} /></View>
            </View>
          ))}
        </View>

        <Text style={s.footer}>Generated by GearFlow</Text>
      </Page>
    </Document>
  );
}
