import { Document, Page, Text, View } from "@react-pdf/renderer";
import { createStyles, formatDate, type PdfBranding } from "./styles";
import { PdfHeader } from "./pdf-header";
import { SummaryBox, equipmentClassLabels, applianceTypeLabels, formatDatePdf } from "./test-tag-pdf-shared";

interface FailedRecordRow {
  testDate: string; testerName: string; result: string;
  testTagAsset: { testTagId: string; description: string; equipmentClass: string; applianceType: string };
  testedBy?: { name: string } | null;
  visualInspectionResult: string; earthContinuityResult: string;
  insulationResult: string; leakageCurrentResult: string;
  polarityResult: string; rcdTripTimeResult: string;
  failureAction: string; failureNotes: string | null;
}

interface Props {
  org: { name: string; email?: string; phone?: string; address?: string; branding?: PdfBranding; logoData?: string | null; iconData?: string | null };
  data: {
    records: FailedRecordRow[];
    failureBreakdown: { visual: number; earthContinuity: number; insulation: number; leakage: number; polarity: number; rcd: number; functional: number };
    total: number;
  };
  filterSummary?: { [key: string]: string | undefined };
}

const failureActionLabels: Record<string, string> = {
  NONE: "None", REPAIRED: "Repaired", REMOVED_FROM_SERVICE: "Removed",
  DISPOSED: "Disposed", REFERRED_TO_ELECTRICIAN: "Referred",
};

export function TestTagFailedItemsPDF({ org, data, filterSummary }: Props) {
  const s = createStyles(org.branding);
  const cw = [50, 90, 40, 50, 55, 80, 55, 100];
  const fb = data.failureBreakdown;

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={s.page}>
        <PdfHeader
          orgName={org.name}
          orgDetails={[org.email, org.phone, org.address].filter(Boolean).join(" | ")}
          docTitle="Failed Items Report"
          docMeta={`${data.total} failures | ${formatDate(new Date())}`}
          branding={org.branding}
          logoData={org.logoData}
          iconData={org.iconData}
          styles={s}
        />

        {filterSummary && (
          <Text style={{ fontSize: 7, color: "#999", marginBottom: 8 }}>
            Filters: {Object.entries(filterSummary).filter(([, v]) => v).map(([k, v]) => `${k}: ${v}`).join(" | ")}
          </Text>
        )}

        <SummaryBox items={[
          { label: "Total Failures", value: data.total },
          { label: "Visual", value: fb.visual },
          { label: "Earth", value: fb.earthContinuity },
          { label: "Insulation", value: fb.insulation },
          { label: "Leakage", value: fb.leakage },
          { label: "Polarity", value: fb.polarity },
          { label: "RCD", value: fb.rcd },
        ]} />

        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.th, { width: cw[0] }]}>Tag ID</Text>
            <Text style={[s.th, { width: cw[1] }]}>Description</Text>
            <Text style={[s.th, { width: cw[2] }]}>Class</Text>
            <Text style={[s.th, { width: cw[3] }]}>Test Date</Text>
            <Text style={[s.th, { width: cw[4] }]}>Tester</Text>
            <Text style={[s.th, { width: cw[5] }]}>Failed Tests</Text>
            <Text style={[s.th, { width: cw[6] }]}>Action</Text>
            <Text style={[s.th, { width: cw[7] }]}>Notes</Text>
          </View>
          {data.records.map((r, i) => {
            const failed: string[] = [];
            if (r.visualInspectionResult === "FAIL") failed.push("Visual");
            if (r.earthContinuityResult === "FAIL") failed.push("Earth");
            if (r.insulationResult === "FAIL") failed.push("Insulation");
            if (r.leakageCurrentResult === "FAIL") failed.push("Leakage");
            if (r.polarityResult === "FAIL") failed.push("Polarity");
            if (r.rcdTripTimeResult === "FAIL") failed.push("RCD");

            return (
              <View key={i} style={i % 2 === 0 ? s.tableRow : s.tableRowAlt}>
                <Text style={[s.td, { width: cw[0] }]}>{r.testTagAsset.testTagId}</Text>
                <Text style={[s.td, { width: cw[1] }]}>{r.testTagAsset.description}</Text>
                <Text style={[s.td, { width: cw[2] }]}>{equipmentClassLabels[r.testTagAsset.equipmentClass] || r.testTagAsset.equipmentClass}</Text>
                <Text style={[s.td, { width: cw[3] }]}>{formatDatePdf(r.testDate)}</Text>
                <Text style={[s.td, { width: cw[4] }]}>{r.testedBy?.name || r.testerName}</Text>
                <Text style={[s.td, { width: cw[5], color: "#dc2626" }]}>{failed.join(", ") || "Overall"}</Text>
                <Text style={[s.td, { width: cw[6] }]}>{failureActionLabels[r.failureAction] || r.failureAction}</Text>
                <Text style={[s.td, { width: cw[7] }]}>{r.failureNotes || "-"}</Text>
              </View>
            );
          })}
        </View>

        <Text style={s.footer}>Generated by GearFlow</Text>
      </Page>
    </Document>
  );
}
