import { Document, Page, Text, View } from "@react-pdf/renderer";
import { createStyles, formatDate, type PdfBranding } from "./styles";
import { PdfHeader } from "./pdf-header";
import { equipmentClassLabels, formatDatePdf } from "./test-tag-pdf-shared";

interface Item {
  testTagId: string; description: string; equipmentClass: string;
  lastTestDate: string | null; nextDueDate: string | null;
  testRecords: { testedBy?: { name: string } | null; testerName: string }[];
}

interface Props {
  org: { name: string; email?: string; phone?: string; address?: string; branding?: PdfBranding; logoData?: string | null; iconData?: string | null };
  data: { items: Item[]; total: number; generatedDate: string };
}

export function TestTagComplianceCertPDF({ org, data }: Props) {
  const s = createStyles(org.branding);
  const cw = [60, 130, 50, 60, 60, 70];

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <PdfHeader
          orgName={org.name}
          orgDetails={[org.email, org.phone, org.address].filter(Boolean).join(" | ")}
          docTitle="Electrical Equipment Compliance Statement"
          docMeta={`Date: ${formatDate(data.generatedDate)}`}
          branding={org.branding}
          logoData={org.logoData}
          iconData={org.iconData}
          styles={s}
        />

        <View style={{ marginBottom: 16 }}>
          <Text style={{ fontSize: 9, lineHeight: 1.6 }}>
            This is to certify that the following electrical equipment owned by {org.name} has been
            inspected and tested in accordance with AS/NZS 3760:2022 and found to be safe for use.
          </Text>
        </View>

        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.th, { width: cw[0] }]}>Tag ID</Text>
            <Text style={[s.th, { width: cw[1] }]}>Description</Text>
            <Text style={[s.th, { width: cw[2] }]}>Class</Text>
            <Text style={[s.th, { width: cw[3] }]}>Last Test</Text>
            <Text style={[s.th, { width: cw[4] }]}>Next Due</Text>
            <Text style={[s.th, { width: cw[5] }]}>Tester</Text>
          </View>
          {data.items.map((item, i) => (
            <View key={i} style={i % 2 === 0 ? s.tableRow : s.tableRowAlt}>
              <Text style={[s.td, { width: cw[0] }]}>{item.testTagId}</Text>
              <Text style={[s.td, { width: cw[1] }]}>{item.description}</Text>
              <Text style={[s.td, { width: cw[2] }]}>{equipmentClassLabels[item.equipmentClass] || item.equipmentClass}</Text>
              <Text style={[s.td, { width: cw[3] }]}>{formatDatePdf(item.lastTestDate)}</Text>
              <Text style={[s.td, { width: cw[4] }]}>{formatDatePdf(item.nextDueDate)}</Text>
              <Text style={[s.td, { width: cw[5] }]}>{item.testRecords[0]?.testedBy?.name || item.testRecords[0]?.testerName || "-"}</Text>
            </View>
          ))}
        </View>

        <View style={{ marginTop: 16 }}>
          <Text style={{ fontSize: 9, fontFamily: "Helvetica-Bold", marginBottom: 4 }}>
            {data.total} items listed. All items held a current test tag as of {formatDate(data.generatedDate)}.
          </Text>
          <Text style={{ fontSize: 8, color: "#666", lineHeight: 1.5 }}>
            This statement covers only the items listed above. It does not constitute a guarantee
            of ongoing safety beyond the stated test dates. Equipment should be visually inspected
            before each use regardless of test tag status.
          </Text>
        </View>

        <View style={{ marginTop: 40, flexDirection: "row", gap: 60 }}>
          <View>
            <View style={{ borderTopWidth: 1, borderTopColor: "#333", width: 180, paddingTop: 4 }}>
              <Text style={{ fontSize: 8, color: "#666" }}>Signature</Text>
            </View>
          </View>
          <View>
            <View style={{ borderTopWidth: 1, borderTopColor: "#333", width: 120, paddingTop: 4 }}>
              <Text style={{ fontSize: 8, color: "#666" }}>Date</Text>
            </View>
          </View>
          <View>
            <View style={{ borderTopWidth: 1, borderTopColor: "#333", width: 160, paddingTop: 4 }}>
              <Text style={{ fontSize: 8, color: "#666" }}>Name / Position</Text>
            </View>
          </View>
        </View>

        <Text style={s.footer}>Generated by GearFlow | AS/NZS 3760:2022 Compliance</Text>
      </Page>
    </Document>
  );
}
