import { Document, Page, Text, View } from "@react-pdf/renderer";
import { createStyles, formatDate, type PdfBranding } from "./styles";
import { PdfHeader } from "./pdf-header";
import { ResultBadgePdf, SummaryBox, formatDatePdf } from "./test-tag-pdf-shared";

interface TestRecordRow {
  testDate: string; result: string;
  testTagAsset: { testTagId: string; description: string };
}

interface Tester {
  name: string;
  totalTests: number;
  passCount: number;
  failCount: number;
  records: TestRecordRow[];
}

interface Props {
  org: { name: string; email?: string; phone?: string; address?: string; branding?: PdfBranding; logoData?: string | null; iconData?: string | null };
  data: { testers: { [key: string]: Tester }; totalRecords: number };
  filterSummary?: { [key: string]: string | undefined };
}

export function TestTagTesterActivityPDF({ org, data, filterSummary }: Props) {
  const s = createStyles(org.branding);
  const cw = [60, 55, 140, 40];
  const testerList = Object.values(data.testers);

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <PdfHeader
          orgName={org.name}
          orgDetails={[org.email, org.phone, org.address].filter(Boolean).join(" | ")}
          docTitle="Tester Activity Report"
          docMeta={`${formatDate(new Date())}`}
          branding={org.branding}
          logoData={org.logoData}
          iconData={org.iconData}
          styles={s}
        />

        {filterSummary && (
          <Text style={{ fontSize: 7, color: "#999", marginBottom: 8 }}>
            Filters: {Object.entries(filterSummary).filter(([, v]) => v).map(([k, v]) => `${k}: ${v}`).join(" | ")}
          </Text>
        )}

        <SummaryBox items={[
          { label: "Total Tests", value: data.totalRecords },
          { label: "Testers", value: testerList.length },
        ]} />

        {testerList.map((tester, ti) => (
          <View key={ti} style={s.section}>
            <Text style={s.sectionTitle}>{tester.name}</Text>
            <View style={{ flexDirection: "row", gap: 16, marginBottom: 6 }}>
              <Text style={{ fontSize: 8 }}>Tests: {tester.totalTests}</Text>
              <Text style={{ fontSize: 8, color: "#166534" }}>Passed: {tester.passCount}</Text>
              <Text style={{ fontSize: 8, color: "#dc2626" }}>Failed: {tester.failCount}</Text>
              <Text style={{ fontSize: 8 }}>Pass rate: {tester.totalTests > 0 ? Math.round((tester.passCount / tester.totalTests) * 100) : 0}%</Text>
            </View>

            <View style={s.table}>
              <View style={s.tableHeader}>
                <Text style={[s.th, { width: cw[0] }]}>Date</Text>
                <Text style={[s.th, { width: cw[1] }]}>Tag ID</Text>
                <Text style={[s.th, { width: cw[2] }]}>Description</Text>
                <Text style={[s.th, { width: cw[3] }]}>Result</Text>
              </View>
              {tester.records.map((r, i) => (
                <View key={i} style={i % 2 === 0 ? s.tableRow : s.tableRowAlt}>
                  <Text style={[s.td, { width: cw[0] }]}>{formatDatePdf(r.testDate)}</Text>
                  <Text style={[s.td, { width: cw[1] }]}>{r.testTagAsset.testTagId}</Text>
                  <Text style={[s.td, { width: cw[2] }]}>{r.testTagAsset.description}</Text>
                  <View style={{ width: cw[3] }}><ResultBadgePdf result={r.result} /></View>
                </View>
              ))}
            </View>
          </View>
        ))}

        <Text style={s.footer}>Generated by GearFlow</Text>
      </Page>
    </Document>
  );
}
