import { Document, Page, Text, View } from "@react-pdf/renderer";
import { createStyles, formatDate, type PdfBranding } from "./styles";
import { PdfHeader } from "./pdf-header";
import { StatusBadgePdf, SummaryBox, formatDatePdf } from "./test-tag-pdf-shared";

interface Item {
  testTagId: string; description: string; serialNumber: string | null;
  location: string | null; lastTestDate: string | null; nextDueDate: string | null; status: string;
}

interface Props {
  org: { name: string; email?: string; phone?: string; address?: string; branding?: PdfBranding; logoData?: string | null; iconData?: string | null };
  data: {
    bulkAsset: { assetTag: string; totalQuantity: number; modelName: string; manufacturer: string | null };
    items: Item[];
    statusCounts: Record<string, number>;
    complianceRate: number;
    registeredCount: number;
  };
}

export function TestTagBulkSummaryPDF({ org, data }: Props) {
  const s = createStyles(org.branding);
  const cw = [55, 55, 55, 55, 55, 45];
  const ba = data.bulkAsset;
  const mismatch = ba.totalQuantity !== data.registeredCount;

  return (
    <Document>
      <Page size="A4" style={s.page}>
        <PdfHeader
          orgName={org.name}
          orgDetails={[org.email, org.phone, org.address].filter(Boolean).join(" | ")}
          docTitle="Bulk Asset T&T Summary"
          docMeta={`${ba.assetTag} - ${ba.modelName} | ${formatDate(new Date())}`}
          branding={org.branding}
          logoData={org.logoData}
          iconData={org.iconData}
          styles={s}
        />

        <View style={s.section}>
          <View style={s.row}>
            <View style={s.col}>
              <Text style={s.label}>Bulk Asset</Text>
              <Text style={s.value}>{ba.assetTag} - {ba.modelName}</Text>
            </View>
            <View style={s.col}>
              <Text style={s.label}>Manufacturer</Text>
              <Text style={s.value}>{ba.manufacturer || "-"}</Text>
            </View>
            <View style={s.col}>
              <Text style={s.label}>Total Quantity</Text>
              <Text style={s.value}>{ba.totalQuantity}</Text>
            </View>
            <View style={s.col}>
              <Text style={s.label}>T&T Registered</Text>
              <Text style={s.value}>{data.registeredCount}</Text>
            </View>
          </View>
          {mismatch && (
            <Text style={{ fontSize: 8, color: "#854d0e", marginTop: 4, backgroundColor: "#fef9c3", padding: 4, borderRadius: 2 }}>
              Note: Registered T&T count ({data.registeredCount}) does not match bulk asset quantity ({ba.totalQuantity}).
            </Text>
          )}
        </View>

        <SummaryBox items={[
          { label: "Compliance", value: `${data.complianceRate}%` },
          { label: "Current", value: data.statusCounts["CURRENT"] || 0 },
          { label: "Due Soon", value: data.statusCounts["DUE_SOON"] || 0 },
          { label: "Overdue", value: data.statusCounts["OVERDUE"] || 0 },
          { label: "Failed", value: data.statusCounts["FAILED"] || 0 },
          { label: "Not Tested", value: data.statusCounts["NOT_YET_TESTED"] || 0 },
        ]} />

        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.th, { width: cw[0] }]}>Tag ID</Text>
            <Text style={[s.th, { width: cw[1] }]}>Serial</Text>
            <Text style={[s.th, { width: cw[2] }]}>Location</Text>
            <Text style={[s.th, { width: cw[3] }]}>Last Test</Text>
            <Text style={[s.th, { width: cw[4] }]}>Next Due</Text>
            <Text style={[s.th, { width: cw[5] }]}>Status</Text>
          </View>
          {data.items.map((item, i) => (
            <View key={i} style={i % 2 === 0 ? s.tableRow : s.tableRowAlt}>
              <Text style={[s.td, { width: cw[0] }]}>{item.testTagId}</Text>
              <Text style={[s.td, { width: cw[1] }]}>{item.serialNumber || "-"}</Text>
              <Text style={[s.td, { width: cw[2] }]}>{item.location || "-"}</Text>
              <Text style={[s.td, { width: cw[3] }]}>{formatDatePdf(item.lastTestDate)}</Text>
              <Text style={[s.td, { width: cw[4] }]}>{formatDatePdf(item.nextDueDate)}</Text>
              <View style={{ width: cw[5] }}><StatusBadgePdf status={item.status} /></View>
            </View>
          ))}
        </View>

        <Text style={s.footer}>Generated by GearFlow</Text>
      </Page>
    </Document>
  );
}
