import { Document, Page, Text, View } from "@react-pdf/renderer";
import { createStyles, formatDate, type PdfBranding } from "./styles";
import { PdfHeader } from "./pdf-header";
import { StatusBadgePdf, SummaryBox, equipmentClassLabels, applianceTypeLabels, formatDatePdf } from "./test-tag-pdf-shared";

interface Item {
  testTagId: string; description: string; equipmentClass: string; applianceType: string;
  location: string | null; nextDueDate: string | null; status: string;
}

interface Props {
  org: { name: string; email?: string; phone?: string; address?: string; branding?: PdfBranding; logoData?: string | null; iconData?: string | null };
  data: { items: Item[]; overdueItems: Item[]; dateFrom: string; dateTo: string };
}

function daysUntil(date: string | null): string {
  if (!date) return "-";
  const diff = new Date(date).getTime() - Date.now();
  const days = Math.ceil(diff / 86400000);
  if (days < 0) return `${Math.abs(days)} overdue`;
  if (days === 0) return "Today";
  return `${days}`;
}

export function TestTagDueSchedulePDF({ org, data }: Props) {
  const s = createStyles(org.branding);
  const cw = [55, 120, 45, 55, 60, 55, 40];
  const allItems = [...data.overdueItems, ...data.items];

  return (
    <Document>
      <Page size="A4" orientation="landscape" style={s.page}>
        <PdfHeader
          orgName={org.name}
          orgDetails={[org.email, org.phone, org.address].filter(Boolean).join(" | ")}
          docTitle="Due For Testing Schedule"
          docMeta={`${formatDate(data.dateFrom)} - ${formatDate(data.dateTo)}`}
          branding={org.branding}
          logoData={org.logoData}
          iconData={org.iconData}
          styles={s}
        />

        <SummaryBox items={[
          { label: "Items Due", value: data.items.length },
          { label: "Already Overdue", value: data.overdueItems.length },
          { label: "Total", value: allItems.length },
        ]} />

        <View style={s.table}>
          <View style={s.tableHeader}>
            <Text style={[s.th, { width: cw[0] }]}>Tag ID</Text>
            <Text style={[s.th, { width: cw[1] }]}>Description</Text>
            <Text style={[s.th, { width: cw[2] }]}>Class</Text>
            <Text style={[s.th, { width: cw[3] }]}>Type</Text>
            <Text style={[s.th, { width: cw[4] }]}>Location</Text>
            <Text style={[s.th, { width: cw[5] }]}>Due Date</Text>
            <Text style={[s.th, { width: cw[6] }]}>Days</Text>
          </View>
          {allItems.map((item, i) => (
            <View key={i} style={i % 2 === 0 ? s.tableRow : s.tableRowAlt}>
              <Text style={[s.td, { width: cw[0] }]}>{item.testTagId}</Text>
              <Text style={[s.td, { width: cw[1] }]}>{item.description}</Text>
              <Text style={[s.td, { width: cw[2] }]}>{equipmentClassLabels[item.equipmentClass] || item.equipmentClass}</Text>
              <Text style={[s.td, { width: cw[3] }]}>{applianceTypeLabels[item.applianceType] || item.applianceType}</Text>
              <Text style={[s.td, { width: cw[4] }]}>{item.location || "-"}</Text>
              <Text style={[s.td, { width: cw[5] }]}>{formatDatePdf(item.nextDueDate)}</Text>
              <View style={{ width: cw[6], flexDirection: "row", alignItems: "center" }}>
                {item.status === "OVERDUE"
                  ? <Text style={[s.td, { color: "#dc2626", fontFamily: "Helvetica-Bold" }]}>{daysUntil(item.nextDueDate)}</Text>
                  : <Text style={s.td}>{daysUntil(item.nextDueDate)}</Text>
                }
              </View>
            </View>
          ))}
        </View>

        <Text style={s.footer}>Generated by GearFlow</Text>
      </Page>
    </Document>
  );
}
